
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-streaming-projectriff-io-v1alpha1-gateway
  failurePolicy: Fail
  name: gateways.streaming.projectriff.io
  rules:
  - apiGroups:
    - streaming.projectriff.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gateway
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-streaming-projectriff-io-v1alpha1-inmemorygateway
  failurePolicy: Fail
  name: inmemorygateways.streaming.projectriff.io
  rules:
  - apiGroups:
    - streaming.projectriff.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - inmemorygateways
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-streaming-projectriff-io-v1alpha1-kafkagateway
  failurePolicy: Fail
  name: kafkagateways.streaming.projectriff.io
  rules:
  - apiGroups:
    - streaming.projectriff.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kafkagateways
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-streaming-projectriff-io-v1alpha1-processor
  failurePolicy: Fail
  name: processors.streaming.projectriff.io
  rules:
  - apiGroups:
    - streaming.projectriff.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - processors
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-streaming-projectriff-io-v1alpha1-pulsargateway
  failurePolicy: Fail
  name: pulsargateways.streaming.projectriff.io
  rules:
  - apiGroups:
    - streaming.projectriff.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pulsargateways
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-streaming-projectriff-io-v1alpha1-stream
  failurePolicy: Fail
  name: streams.streaming.projectriff.io
  rules:
  - apiGroups:
    - streaming.projectriff.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - streams
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-streaming-projectriff-io-v1alpha1-gateway
  failurePolicy: Fail
  name: gateways.streaming.projectriff.io
  rules:
  - apiGroups:
    - streaming.projectriff.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gateway
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-streaming-projectriff-io-v1alpha1-inmemorygateway
  failurePolicy: Fail
  name: inmemorygateways.streaming.projectriff.io
  rules:
  - apiGroups:
    - streaming.projectriff.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - inmemorygateways
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-streaming-projectriff-io-v1alpha1-kafkagateway
  failurePolicy: Fail
  name: kafkagateways.streaming.projectriff.io
  rules:
  - apiGroups:
    - streaming.projectriff.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kafkagateways
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-streaming-projectriff-io-v1alpha1-processor
  failurePolicy: Fail
  name: processors.streaming.projectriff.io
  rules:
  - apiGroups:
    - streaming.projectriff.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - processors
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-streaming-projectriff-io-v1alpha1-pulsargateway
  failurePolicy: Fail
  name: pulsargateways.streaming.projectriff.io
  rules:
  - apiGroups:
    - streaming.projectriff.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pulsargateways
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-streaming-projectriff-io-v1alpha1-stream
  failurePolicy: Fail
  name: streams.streaming.projectriff.io
  rules:
  - apiGroups:
    - streaming.projectriff.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - streams
  sideEffects: None
