
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-knative-projectriff-io-v1alpha1-adapter
  failurePolicy: Fail
  name: adapters.knative.projectriff.io
  rules:
  - apiGroups:
    - knative.projectriff.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - adapters
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-knative-projectriff-io-v1alpha1-deployer
  failurePolicy: Fail
  name: deployers.knative.projectriff.io
  rules:
  - apiGroups:
    - knative.projectriff.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - deployers
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-knative-projectriff-io-v1alpha1-adapter
  failurePolicy: Fail
  name: adapters.knative.projectriff.io
  rules:
  - apiGroups:
    - knative.projectriff.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - adapters
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-knative-projectriff-io-v1alpha1-deployer
  failurePolicy: Fail
  name: deployers.knative.projectriff.io
  rules:
  - apiGroups:
    - knative.projectriff.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - deployers
  sideEffects: None
